### ISSUE TITLE
HADOOP_CMD getting lost...

### ISSUE THREAD

**Issue by bhermont** [RevolutionAnalytics/rhdfs#16]
Hi Antonio,

I've faced a scenario where I call a mapreduce (rmr) from a Shell script inside a Mapper (This is how Oozie launches a Shell action)

Here is the flow:
Oozie Launcher Job -> Lancher Map only task where shell script (Rscript myscript.r) executes -> StreamJob -> Mapper / Reducers
## myscript.r

Sys.setenv(JAVA_HOME="/usr/jdk64/jdk1.7.0_67")
Sys.setenv(HADOOP_CMD="/usr/bin/hadoop")
Sys.setenv(HADOOP_HOME="/usr/hdp/2.2.6.0-2800/hadoop")
Sys.setenv(HADOOP_STREAMING="/usr/hdp/2.2.6.0-2800/hadoop-mapreduce/hadoop-streaming.jar")
library("rhdfs")
library("rmr2")
hdfs.init()
library(Matrix)
<mapreduce call here>
## Logs 

Launcher Job (Job that launches  Map only task)
    On this map, the following shell script is executed as a system call (Rscript myscript.r) - Here HADOOP_CMD is set correctly, but an error on the mr function is logged (Probably due the Streaming Mapper error when a hdfs function is called from inside the mr function). Launcher (Mapper) log:

```
Loading required package: methods
Loading required package: rJava

HADOOP_CMD=/usr/bin/hadoop

Be sure to run hdfs.init()
Please review your hadoop settings. See help(hadoop.settings)
Error in mr(map = map, reduce = reduce, combine = combine, vectorized.reduce,  : 
  hadoop streaming failed with error code 15
Calls: getTags -> mapreduce -> mr
```

The rmr streaming starts a StreamJob which can have Mappers and Reducers. StreamJob (Mapper) log:

```
    Log Type: stderr
    Log Upload Time: Thu Aug 06 19:24:41 -0400 2015

    Log Length: 2722

    Loading objects:
    Loading objects:
      backend.parameters
      combine
    Please review your hadoop settings. See help(hadoop.settings)
      combine.file
      combine.line
      debug
      default.input.format
      default.output.format
      in.folder
      in.memory.combine
      input.format
      libs
      map
      map.file
      map.line
      out.folder
      output.format
      pkg.opts
      postamble
      preamble
      profile.nodes
      reduce
      reduce.file
      reduce.line
      rmr.global.env
      rmr.local.env
      save.env
      tempfile
      vectorized.reduce
      verbose
      work.dir
    Loading required package: methods
    Loading required package: rJava
    Loading required package: rhdfs
    Error : .onLoad failed in loadNamespace() for 'rhdfs', details:
      call: fun(libname, pkgname)
      error: Environment variable HADOOP_CMD must be set before loading package rhdfs
    Warning in FUN(X[[i]], ...) : can't load rhdfs
    Loading required package: rmr2
    Loading required package: Matrix
```

However, calling the myscript.r from command line works fine.

Here is my question:
Should rmr propagate the environment envs in this case, or this should be responsibility of the enviroment to provide the value for the HADOOP_CMD variable?

**Comment by piccolbo** [comment]
Please submit to the rmr2 issue tracker.

**Comment by bhermont** [comment]
Done!
